# Generated by Django 5.2.5 on 2025-09-18 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_goal_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('noon', 'Noon'), ('evening', 'Evening'), ('bedtime', 'Bedtime')], max_length=10, null=True)),
                ('date_taken', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_records', to='tracking.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_taken_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
                'unique_together': {('medication', 'user', 'scheduled_time', 'date_taken')},
            },
        ),
    ]
