# Generated by Django 5.2.5 on 2025-10-31 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nudge_type', models.CharField(choices=[('health', 'Health'), ('medication', 'Medication'), ('activity', 'Activity'), ('wellness', 'Wellness'), ('general', 'General')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='agent_nudge_user_id_f054a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionNudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('preference', 'Preference'), ('health_update', 'Health Update'), ('medication', 'Medication'), ('activity', 'Activity'), ('feedback', 'Feedback'), ('general', 'General')], default='general', max_length=20)),
                ('question', models.TextField()),
                ('user_response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('skipped', 'Skipped'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_nudges', to='agent.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='agent_quest_user_id_0d1ef5_idx'), models.Index(fields=['status', '-created_at'], name='agent_quest_status_364099_idx')],
            },
        ),
    ]
