# Generated by Django 5.2.5 on 2025-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_goalnudge'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike'), ('love', 'Love')], max_length=10, null=True),
        ),
    ]
