# Generated by Django 5.2.5 on 2025-11-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_page_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('chunks_count', models.IntegerField(default=0)),
                ('extracted_text_length', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
