# Generated by Django 5.2.5 on 2025-11-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_globaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='s3_object_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
