import { MedicationModel, NewMedication } from '../types';
import apiClient from './apiClient';

/**
 * Posts a new medication to the server.
 * In a real application, this would also require an authentication token.
 *
 * @param medicationData The data for the new medication (name, dosage, frequency).
 * @returns The newly created medication object, including the ID generated by the server.
 */
export const postNewMedication = async (medicationData: NewMedication): Promise<MedicationModel> => {
    try {
        // Map the camelCase frontend model to the snake_case backend payload
        const payload = {
            name: medicationData.name,
            dosage: medicationData.dosage,
            notes: medicationData.notes,
            frequency_type: medicationData.frequencyType,
            reminder_times: medicationData.reminderTimes,
            is_active: true, // New medications are active by default
        };

        const response = await apiClient.post<MedicationModel>(`tracking/medications/`, payload);
        return response.data;
    } catch (error) {
        // Log the detailed error for debugging purposes
        console.error('Failed to post new medication:', error);
        
        // Throw a user-friendly error to be handled by the store
        throw new Error('An error occurred while saving the medication. Please check your connection and try again.');
    }
};
