# Generated by Django 5.2.5 on 2025-09-09 08:37

from django.db import migrations, models
import uuid


def fix_duplicate_empty_emails(apps, schema_editor):
    """Fix duplicate empty email addresses before applying unique constraint."""
    User = apps.get_model('profiles', 'User')
    users_with_empty_emails = User.objects.filter(email='')
    
    for user in users_with_empty_emails:
        # Generate unique placeholder emails for all users with empty emails
        placeholder_email = f"placeholder_{uuid.uuid4().hex[:8]}@temp.local"
        user.email = placeholder_email
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_questionnairetemplate_and_more'),
    ]

    operations = [
        # First, fix duplicate empty emails
        migrations.RunPython(fix_duplicate_empty_emails, migrations.RunPython.noop),
        # Remove username field
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        # Then apply unique constraint to email
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
