# Generated by Django 5.2.5 on 2025-09-09 08:54

import profiles.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', profiles.models.UserManager()),
            ],
        ),
    ]
