# Generated by Django 5.2.5 on 2025-10-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_user_date_of_birth_user_gender_user_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, help_text='Points earned from completing goals'),
        ),
    ]
