# Generated by Django 5.2.5 on 2025-10-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_user_date_of_birth_user_gender_user_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time FCM token was updated', null=True),
        ),
    ]
