# Generated by Django 5.2.5 on 2025-10-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_user_fcm_token_user_fcm_token_updated_at'),
        ('profiles', '0007_user_points'),
    ]

    operations = [
    ]
