# Generated by Django 5.2.5 on 2025-10-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_merge_20251015_1238'),
        ('profiles', '0008_remove_user_fcm_token_and_more'),
    ]

    operations = [
    ]
