# Generated by Django 5.2.5 on 2025-10-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_userpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.CreateModel(
            name='ForestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, help_text='Total points earned by the user')),
                ('points_per_tree', models.IntegerField(default=100, help_text='Points required to grow one tree')),
                ('current_cycle_points', models.IntegerField(default=0, help_text='Points in current tree growth cycle')),
                ('completed_trees', models.IntegerField(default=0, help_text='Total number of trees completed')),
                ('total_mindfulness', models.IntegerField(default=0, help_text='Total mindfulness/mind goals completed')),
                ('total_social_connection', models.IntegerField(default=0, help_text='Total social connection goals completed')),
                ('total_nutrition', models.IntegerField(default=0, help_text='Total nutrition goals completed')),
                ('total_medications', models.IntegerField(default=0, help_text='Total medications taken')),
                ('total_activity', models.IntegerField(default=0, help_text='Total activity goals completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forest_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forest Progress',
                'verbose_name_plural': 'Forest Progress',
            },
        ),
    ]
