# Generated by Django 5.2.5 on 2025-10-23 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_user_points_forestprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestprogress',
            name='current_tree_activity',
            field=models.IntegerField(default=0, help_text='Activity goals for current tree'),
        ),
        migrations.AddField(
            model_name='forestprogress',
            name='current_tree_medications',
            field=models.IntegerField(default=0, help_text='Medications for current tree'),
        ),
        migrations.AddField(
            model_name='forestprogress',
            name='current_tree_mindfulness',
            field=models.IntegerField(default=0, help_text='Mindfulness goals for current tree'),
        ),
        migrations.AddField(
            model_name='forestprogress',
            name='current_tree_nutrition',
            field=models.IntegerField(default=0, help_text='Nutrition goals for current tree'),
        ),
        migrations.AddField(
            model_name='forestprogress',
            name='current_tree_social',
            field=models.IntegerField(default=0, help_text='Social goals for current tree'),
        ),
        migrations.AlterField(
            model_name='forestprogress',
            name='points_per_tree',
            field=models.IntegerField(default=80, help_text='Points required to grow one tree (20 per stage x 4 stages)'),
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_number', models.IntegerField(help_text='Sequential number of this tree for the user')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('mindfulness_count', models.IntegerField(default=0, help_text='Mindfulness goals completed for this tree')),
                ('social_count', models.IntegerField(default=0, help_text='Social goals completed for this tree')),
                ('nutrition_count', models.IntegerField(default=0, help_text='Nutrition goals completed for this tree')),
                ('medications_count', models.IntegerField(default=0, help_text='Medications taken for this tree')),
                ('activity_count', models.IntegerField(default=0, help_text='Activity goals completed for this tree')),
                ('total_points', models.IntegerField(default=80, help_text='Total points accumulated for this tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'tree_number')},
            },
        ),
    ]
