# Generated by Django 5.2.5 on 2025-10-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_forestprogress_current_tree_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_achievement', models.IntegerField(default=5, help_text='Points awarded per completed goal/achievement')),
                ('points_per_stage', models.IntegerField(default=20, help_text='Points required per tree stage (seed/sprout/sapling/tree)')),
                ('stages_per_tree', models.IntegerField(default=4, help_text='Number of stages per complete tree')),
                ('category_mappings', models.JSONField(default=dict, help_text='Mapping of goal categories to display info')),
                ('stage_definitions', models.JSONField(default=dict, help_text='Definition of each tree stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
            ],
            options={
                'verbose_name': 'Forest Configuration',
                'verbose_name_plural': 'Forest Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='forestprogress',
            name='points_per_tree',
        ),
    ]
