# Generated by Django 5.2.5 on 2025-10-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_forestconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestconfiguration',
            name='points_per_achievement',
            field=models.IntegerField(default=25, help_text='Points awarded per completed goal/achievement'),
        ),
        migrations.AlterField(
            model_name='forestconfiguration',
            name='points_per_stage',
            field=models.IntegerField(default=50, help_text='Points required per tree stage (seed/sprout/sapling/tree)'),
        ),
    ]
